# Generated by Django 2.2.26 on 2022-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
