# Generated by Django 2.2.26 on 2022-04-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
    ]
