# Generated by Django 2.2.26 on 2022-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
