# Generated by Django 2.2.26 on 2022-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0002_auto_20220406_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=255,
                                   null=True),
        ),
    ]
