# Generated by Django 2.2.26 on 2022-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20220411_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='status',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
