# Generated by Django 2.2.26 on 2022-04-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20220411_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='max_apps',
            field=models.IntegerField(default=1),
        ),
    ]
