# Generated by Django 2.2.26 on 2022-04-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptions_max_apps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='user_id',
            new_name='user',
        ),
    ]
