# Generated by Django 2.2.26 on 2022-04-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20220412_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='max_apps',
        ),
    ]
