# Generated by Django 2.2.26 on 2022-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='domain_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='framework',
            field=models.CharField(choices=[('django', 'Django'), ('react_native', 'React Native')], default='django', max_length=20),
        ),
        migrations.AddField(
            model_name='apps',
            name='screenshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='apps',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
