# Generated by Django 2.2.26 on 2022-04-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20220410_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='apps',
            name='subscription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps_subscription_id', to='subscriptions.Subscriptions'),
        ),
    ]
