# Generated by Django 2.2.26 on 2022-04-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20220412_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_subscription_id', to='subscriptions.Subscriptions'),
        ),
    ]
